POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video 01",
    "description": "esse é a descriçao",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/
Content-Type: application/json

{
    "title": "video 01",
    "description": "esse é a descriçao",
    "duration": 180
}
